# Generated by Django 4.2.13 on 2026-04-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200)),
                ('jumlah_stok', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('satuan', models.CharField(choices=[('kg', 'Kilogram'), ('ons', 'Ons'), ('pcs', 'Pieces'), ('pack', 'Pack'), ('zak', 'Zak'), ('liter', 'Liter'), ('unit', 'Unit')], default='kg', max_length=20)),
                ('tanggal_update', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventori',
                'verbose_name_plural': 'Inventori',
                'ordering': ['nama_barang'],
            },
        ),
        migrations.CreateModel(
            name='InventoriMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventori.inventori')),
            ],
            options={
                'verbose_name': 'Pergerakan Stok',
                'verbose_name_plural': 'Pergerakan Stok',
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
