# Generated by Django 4.2.13 on 2026-04-22 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=15)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kategori', models.CharField(choices=[('bahan_baku', 'Bahan Baku'), ('operasional', 'Operasional'), ('gaji', 'Gaji Karyawan'), ('listrik_air', 'Listrik & Air'), ('lainnya', 'Lainnya')], default='operasional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengeluaran',
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=15)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('kategori', models.CharField(choices=[('penjualan', 'Penjualan Tempe'), ('titip_jual', 'Titip Jual'), ('lainnya', 'Lainnya')], default='penjualan', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemasukan',
                'verbose_name_plural': 'Pemasukan',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
