# Generated by Django 4.2.13 on 2026-04-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengaturan', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('telegram', 'Telegram'), ('notifikasi', 'Notifikasi'), ('aplikasi', 'Aplikasi')], max_length=20)),
                ('nilai', models.TextField(blank=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
                'unique_together': {('nama_pengaturan', 'jenis')},
            },
        ),
    ]
