# Generated by Django 4.2.13 on 2026-04-25 15:51

import apps.pengaturan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_hp', models.CharField(blank=True, max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(default=apps.pengaturan.models.generate_verification_code, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Subscriber',
                'verbose_name_plural': 'Telegram Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
